### PR TITLE
autopep8 integration

### PR DESCRIPTION
**Pull request by FredericGuilbault**
autopep8 is a code quality tool that ensure coherent and clean coding style. 

This is a minimal integration of the tool. At this point, it's mainly adjusting spaces and tabs. 

The point here is to help having clean commits. And automating the process of code quality revision.

### CODE REVIEW

**Comment by sailoog** [comment]
bufff this one does hurt. This commit affects to all scripts and there are conflicts with some parts we are still developing. Please push again when v2.x.x development is more advanced, maybe translations stage would be a good time. We apreciate your commits, if you have plans of doing important commits like this please inform us to avoid conflicts. Thanks.

**Comment by FredericGuilbault** [comment]
Good, it's not a big deal. I probably won't be able to rebase so Im better closing this branch for now. Ill create a new pull request when the time will come.

**Comment by FredericGuilbault** [comment]
@sailoog 
> if you have plans of doing important commits like this please inform us to avoid conflicts. Thanks.
Oh I assumed the github was up to date :s 

Im not sure where im going with this exactly lol. 
For now, im just trying to integrate it in my raspberry OS. So ATM it's just the integration problems I  came across. 

---
In a second time, there will be some features that I won't manage with openplotter. 
( Im a better sysadmin then coder. So I will try to avoid depending on userland GUI to manage things that can be done directly in the OS.) 

So I guess I will comeback with pull request about config settings to hide/disable features. 

I have trust in where you are going with this project and for a fact, I don't want to have any forked feature or code to maintain.  So I hope it will be compatible with the vision you have. 

When the time will come. Should I open issues to discuss the best approach before making any commits regarding hide/disable feature ?

**Comment by sailoog** [comment]
Yes, open as many issues as you need. We have always had intentions of porting OP to different systems than raspbian and that can be useful. 

I am better coder than sys admin so it is perfect :)

From your latest commits I can see that the first feature you want to remove is pypilot. I am afraid there are more places where something should be fixed, see at read_sensors_d.py and classes/add_i2c.py

**Pull request closed without merging**
