### PR TITLE
Feature/add branch to update script

### PR DESCRIPTION
**Pull request by aayaffe**
In order to easily work with feature branches on main and forked repos, I've added a branch option to the OpenPlotter update script. 
When no branch is given the former logic is applied (stable from master branch and beta from beta branch).

### CODE REVIEW

**Comment by aayaffe** [comment]
If you will still be obtaining the code from github, supporting other repos and branches would be appreciated.

**Comment by sailoog** [comment]
I will

**Comment by jamesewilliamson** [comment]
vote+1 i have one setup just for testing breaking :)

**Comment by sailoog** [comment]
This has already been added to v1.x.x closing...

**Pull request closed without merging**
