### PR TITLE
updated to allow non /dev/ttyUSB devices to work. The device type is …

### PR DESCRIPTION
**Pull request by jongough**
…maintained in the config file to ensure the udev rules can be built correctly

### CODE REVIEW

**Comment by jongough** [comment]
I made this change as the usb gps units I am using do not show up as ttyUSB* but as ttyACM*. This change should allow all types to be maintained and to build the correct udev rules.

**Comment by sailoog** [comment]
Thanks @jongough

(I ping @e-sailing who wrote this part)

Just to clarify... I was told that remembering ports (not devices) was only possible for ttyUSB devices. Do you mean that it will work for any type?

**Comment by sailoog** [comment]
Note that remembering devices works already for ttyACM and for any device.

**Comment by jongough** [comment]
This change is for devices that do not have a unique serial number and therefore are identified by the USB position. The original code assumed that all USB devices would turn up as /dev/ttyUSB* when it was writing the "10-openplotter.rules". This change allows the device name, in my case /dev/ttyACM* to be written to this rule. This allows the device to be correctly identified when it is plugged in or the system is started. 
The code uses the device as shown in the "add" windows to build this. This device is saved in the openplotter.conf file along with the other fields already saved.
If your devices have a unique serial number the udev process is different and probably works OK as the vendor id, product id and serial number is used to identify the device.

**Comment by e-sailing** [comment]
It is a bug and you solved it. I tested ttyACM0 with remember by dev. OK
I tested ttyACM0 with remember by port. Doesn't work.
Your changes solved the problem. Thanks!

**Comment by sailoog** [comment]
Great, thanks!

**Comment by sailoog** [comment]
Merged on master and v0.9.0 branches

**Pull request merged**
