### PR TITLE
Added rtl8188eu

### PR DESCRIPTION
**Pull request by jongough**
This pull adds the hostapd file needed for rtl8188eu wifi adapters, but there is a need for the firmware to be installed and a different version of the 8188eu usb module. I have these, but I am not sure where to put them to make the available in a normal install. If you let me know I will supply them.

Regards
   Jon

### CODE REVIEW

**Comment by sailoog** [comment]
Thanks!
I don't have any rtl8188eu, so I have some questions...

It works for you on OpenPlotter?

For rtl8188eu you set:
driver=''
wpa='3'
hw_mode='g'
channel='11'
Don't you need to define driver?
Are the rest of options mandatory?

For the rest of chipsets you define:
wpa='1'
hw_mode='b'
channel='6'
Do you think this will work for all the chipsets? I could test it.

I know how to get and install the new module for rtl8188eu because I do the same for rtl8192eu on every OP release.

This request comes at the right moment because a need to rewrite this script to make it more Raspberry 2/3 friendly. Thanks!

**Comment by jongough** [comment]
I updated the script so that my wifi adapter would work. For this adapter you cannot specify the driver, if you do you get an error when trying to start the access point saying 'driver not found'. So looking around I found that you need to remove the driver line altogether, then the access point will default to the same driver that is specified by the other adapters, but it has to do this itself. Also, by default the access point was working on 'b' mode and was a bit slow, making it 'g' speed it up. It would seem that most adapters default to channel 6 which in marinas makes it a bit congested, so I wanted to try a different one. The wpa=3 allows both WPA and WPA2 to be used, windows seems to be a bit particular about this, so windows 10 would not connect reliably without using WPA2. I am still looking at windows xp, as it sometimes does and sometimes doesn't connect.

The changes to the script just make it easier to change settings rather than have to change the 'long' string which is more error prone. I set the defaults to what was in the original script so that the other adapters are not affected, I then change the default for the 8188eu to the settings I found works.

If you could install the 8188eu modules in a test version the I can install that and try out the changes to make sure they work. I think you will need to generate both the driver modules and the hostapd modules from the same source tree as they seem rather sensitive to each other. Certainly the ones I used create a lsmod link of 8188eu which, during installation, blacklists the r8188eu modules.

One other thing, I was thinking that there needs to be a screen/dialog that allows the user to change these parameters more easily. I am not sure if it should be in the openplotter dialog as that is getting rather big unless it can be made to have multi row tabs. I really know nothing about python, so I don't know if this is possible. In wxWidgets with c++ it is, but....

Jon

**Comment by sailoog** [comment]
Hi Jon,

I think the best option will be allowing to change these parameters to users as you suggested. So, if I am not wrong these are the custom parameters and their possible values:

wpa=WPA/WPA2/both
hw_mode=a/b/g/ad
channel=1 to 11 (I think 12,13 and 14 have restrictions in some countries)

It should be a "default" option too.

If you agree I can merge your commits, make these modifications, install the special module for 8188eu and create a beta image so you can test it.

thanks again

**Comment by jongough** [comment]
I have been looking at the code for the display and it seems as if you are hand coding the display elements. I have been using wxFormBuilder when doing work on OpenCPN and found this easier to work with than straight code. I then create my modifications in a class based on the one generated by wxFormBuilder. Do you use any tools to create the display code? If so, what are they?

I would like to add the wifi values to the display to avoid users having to change the base code, and, of course, save these values to be used when openplotter is restarted.

Is there a forum where ideas are discussed about openplotter?

Thanks
Jon

**Comment by sailoog** [comment]
Hi Jon,
So, are you the author of ocpn_draw_pi? congratulations! great work.

We discuss about OpenPlotter here: http://forum.openmarine.net join us please.

I have merged your changes and worked on it, probably today I will push changes. I am adding the new custom fields channel, wpa and hw_mode to the interface so do not worry about it. I am used to create interfaces manually and I am not using any tools on openplotter for this. I didn't know wxFormBuilder, I will give it a go on the next project for sure.

Please I need to confirm something to be sure that 8188eu will work with this new changes. Could you test this on openplotter:

- connect your 8188eu working device
- sudo pip install pyudev
- create a file named test.py with:

```
import pyudev
context = pyudev.Context()
for device in context.list_devices(subsystem='net'):
	for key, value in device.iteritems():
		print key+': '+value
	print 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```
- run: python test.py
- you will get a device list with some properties, I would need to know if your device is detected as: ID_NET_DRIVER:rtl8188eu

Thanks!

**Comment by jongough** [comment]
The wlan0 device says 'r8188eu'.

**Comment by sailoog** [comment]
Ok, thanks! Now I am quite sure r8188eu will work with the next v0.8.0 release as r8192eu do. I will notify you when you can test it.
I have added the customs fields hw_mode, wpa and channel to v0.8.0 branch. If you want test it here are the instructions: http://www.sailoog.com/en/blog/test-openplotter-v080beta

I use just a code editor (sublime text) to write python, not IDE. I don't feel comfortable working on the pi directly so I work on my ubuntu and send changes to the pi by network for testing.

**Pull request merged**
