### PR TITLE
backwards compatibility and fix

### PR DESCRIPTION
**Pull request by e-sailing**
added 4 decimal for nmea 0183 generator
add offline Help

### CODE REVIEW

**Comment by dmdelorme** [comment]
You might want to go a few more decimal places as i have found openCPN 4.5.0 Barometer needs to be in the value range of 1.1 to .9 or so for all the gages to work.

**Comment by e-sailing** [comment]
I saw your branch after I edited the python script. In the forum they wanted 4 decimal places. If you have a Barometer on NMEA2000 you only have 3 decimal places. Do you really need 6?
btw: In the past there was an error in signalk converting nmea2000 to propulsion.*.revolution (they used rpm instead of Hz;  Hz is SI-unit) when they changed it I had to multiply propulsion.*.revolution * 60.

**Comment by dmdelorme** [comment]
It is a rounding issue as the Sk value is in Pa "102954.000  Opencpn Wants Bar so i divide by 100000
                                          
and get  1.029040 round 6  1029.040        
               1.0290 round 4     1029.000
                1.03 round 2        1030.000
                then OpenCPN *1000

I would prefer if OpenCPN just read SK as we are just doing a lot of extra stuff or Ditch the gauges and use freeboard. 
I am fine with 4 I was just being a geek I did not see the Forum posts and made the change for my self.

**Comment by dmdelorme** [comment]
I will try this new code as i have couple of pi3 set up for testing

**Comment by dmdelorme** [comment]
looks good freeboard is acting up but it might be my flow

**Pull request merged**
